-- Add all required columns if they don't exist
ALTER TABLE Users 
ADD COLUMN IF NOT EXISTS password VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS mobile VARCHAR(15) DEFAULT NULL,
MODIFY COLUMN name VARCHAR(100) DEFAULT 'User',
MODIFY COLUMN firebase_uid VARCHAR(128) UNIQUE NOT NULL,
MODIFY COLUMN email VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci UNIQUE NOT NULL;